require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3.4
  EnabledByDefault: true
  NewCops: enable

### Bundler ###

Bundler/GemComment:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

### Style ###

Style/Documentation:
  Enabled: false
