services:
  app:
    image: dedski-users-api:latest
    build:
      context: ./
      args:
        USER_GRUP: ${USER_GRUP}
        USER_NAME: ${USER_NAME}
        USER_PASW: ${USER_PASW}
        ROOTS_GID: ${ROOTS_GID}
        ROOTS_UID: ${ROOTS_UID}
    depends_on:
      - db
    volumes:
      - ./:/opt/app
    env_file:
      - .env
    ports:
      - 3000:3000
      - 6969:6969

  db:
    image: postgres:alpine3.20
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASW}

networks:
  default:
    name: dedski
    ipam:
      driver: default
      config:
        - subnet: "69.0.0.0/24"

volumes:
  postgres:
