default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%=  ENV.fetch('DATABASE_PORT', 5432) %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASW"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: users-api_development

test:
  <<: *default
  database: users-api_test

production:
  <<: *default
  database: users-api_production
